### ISSUE TITLE
Create Matches Page

### ISSUE THREAD

**Issue by s-rathyen** [manoafitnessfinder/app#20]
Do work for this issue in brach issue-#20.

- On the left side, create a 'filter' element which allows the user to filter based on interests, level, etc.
- On the right side, display all profiles that match the filtered data.

**Comment by pmccrind** [comment]
![events](https://user-images.githubusercontent.com/35245519/80892637-61e2e000-8c67-11ea-842a-ad7f65d6ec0b.png)
Matches page turned into the events page. Fliters to implemented in another issue.
