### ISSUE TITLE
Create Multi-selectfield for Profile Page

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#23]
Do work for this issue in branch issue-#23.

* Add the interests as a multiselectfield button.
* Add at least Running, Hiking, and Climbing, and any other relevant interests.

**Comment by s-rathyen** [comment]
<img width="1789" alt="Screen Shot 2020-04-21 at 8 52 45 PM" src="https://user-images.githubusercontent.com/38778256/79950077-39aae400-8412-11ea-8c73-64854cc92ae8.png">
