### ISSUE TITLE
Edit: Edit Profile Page

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#24]
Do work for this issue in branch issue-#24.

* Make the Edit Profile Page look and feel like the other pages
* Make the fonts the same
* Use the site's color for other fields

**Comment by s-rathyen** [comment]
![Uploading Screen Shot 2020-04-21 at 8.48.36 PM.png…]()

**Comment by s-rathyen** [comment]
<img width="1789" alt="Screen Shot 2020-04-21 at 8 48 36 PM" src="https://user-images.githubusercontent.com/38778256/79949700-a70a4500-8411-11ea-973f-5b66f5ba9e66.png">

**Comment by s-rathyen** [comment]
<img width="1789" alt="Screen Shot 2020-04-21 at 9 05 27 PM" src="https://user-images.githubusercontent.com/38778256/79951179-f05b9400-8413-11ea-8bd4-423a50f34240.png">
Fonts match, all issue requirements now satisfied.
