### ISSUE TITLE
Add Edit Button to Profile

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#25]
Do work for this issue in the branch issue-#25.

* Add a button on the profile page that takes the user to the edit profile page.
* Ensure they are editing their own profile.

**Comment by s-rathyen** [comment]
<img width="1789" alt="Screen Shot 2020-04-21 at 8 48 47 PM" src="https://user-images.githubusercontent.com/38778256/79950198-65c66500-8412-11ea-864f-0c8ed35578c4.png">
Sorry - didn't realize this was a separate issue, so I did the work for it in branch issue-#24.
