### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#3]
Please do work for this task in branch #3.

- Create a logo that will be displayed on the navbar for every page on site.

**Comment by s-rathyen** [comment]
![20200415_ICS314_RathyenMFFLogoV01](https://user-images.githubusercontent.com/38778256/79314597-969c1c80-7e9d-11ea-8da6-0b011540151e.png)
![20200415_ICS314_RathyenMFFLogoV02](https://user-images.githubusercontent.com/38778256/79314599-97cd4980-7e9d-11ea-9e1a-174a1830d1ab.png)
Created two versions.

**Comment by s-rathyen** [comment]
![6d9b7c](https://user-images.githubusercontent.com/38778256/79542163-d7736d00-8026-11ea-9f60-9d480ce8a3da.png)

Decided on final color for logo/site.
