### ISSUE TITLE
Create Testimonials and Contact Page

### ISSUE THREAD

**Issue by Lsrock** [manoafitnessfinder/app#33]

**Comment by pmccrind** [comment]
![test_1](https://user-images.githubusercontent.com/35245519/80564154-be54af80-8988-11ea-8cc6-14c5f16de5a9.PNG)
![test_2](https://user-images.githubusercontent.com/35245519/80564160-c14fa000-8988-11ea-8c52-b6e22ecf1ca3.PNG)
![contact_us](https://user-images.githubusercontent.com/35245519/80564162-c3b1fa00-8988-11ea-82ea-a69a2ab4f4e9.PNG)
