### ISSUE TITLE
Cleanup up Stlye.css

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#36]
Do work for this issue in branch issue-#36.
- Remove redundancies in style.css
- Fix class names
- Comment where necessary

**Comment by s-rathyen** [comment]
<img width="1538" alt="Screen Shot 2020-05-13 at 6 22 38 PM" src="https://user-images.githubusercontent.com/38778256/81892403-c004a280-9546-11ea-9c9c-f4d1a0475f69.png">
