### ISSUE TITLE
User Profile Top Bar

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#38]
Do work for this issue in branch issue-#38.

* Edit the top of the user page

**Comment by s-rathyen** [comment]
<img width="1789" alt="Screen Shot 2020-05-02 at 7 16 49 PM" src="https://user-images.githubusercontent.com/38778256/80914372-d01ab780-8ce6-11ea-94db-10c909ca95b4.png">
<img width="1789" alt="Screen Shot 2020-05-02 at 7 33 45 PM" src="https://user-images.githubusercontent.com/38778256/80914376-d3ae3e80-8ce6-11ea-8402-55f291802524.png">
