### ISSUE TITLE
Clean up EsLint Errors

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#39]
Do work for this issue in branch issue-#39.

**Comment by pmccrind** [comment]
Eslint errors resolved after M2.

**Comment by njanders9124** [comment]
_ lodash imports breaking actual underscore functions
Disabled eslint inspections on Event renders using the _.findWhere and _.where functions

**Comment by pmccrind** [comment]
![eslint_errors](https://user-images.githubusercontent.com/35245519/81892988-2807b880-9548-11ea-97ae-9eca81b7ad2e.PNG)
