### ISSUE TITLE
Create Schedule Page

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#4]
Please do work for this task in branch #4.

* Display list of upcoming events.
* Hide this page unless a user is signed in.
* Tie in with the notes

Page Layout:
- Left side of page will have an "add a new event" element which allows users to choose by event type, time, date, and associated users
- Middle of page displays upcoming events starting from soonest first

**Comment by s-rathyen** [comment]
<img width="1799" alt="Screen Shot 2020-04-25 at 12 34 36 AM" src="https://user-images.githubusercontent.com/38778256/80278094-425c1e00-868f-11ea-8ebf-fb58138d2c3d.png">
Schedule page created. Will improve functionality/UI in a different branch.
