### ISSUE TITLE
My Events Page

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#44]
Do work for this issue in branch issue-#44.

Implement a My Events Page which should display
* All the User's Events & the User's Friends Events
* A new page for just the User's Events.

**Comment by njanders9124** [comment]
This issue was split into both the Mv Events page and the Friend Fee page, both of which can be found in their own issues.

**Comment by s-rathyen** [comment]
<img width="1791" alt="Screen Shot 2020-05-13 at 6 20 49 PM" src="https://user-images.githubusercontent.com/38778256/81892304-7f0c8e00-9546-11ea-920e-c88588f8bd7f.png">
