### ISSUE TITLE
Resize the images to the Rendered Size

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#58]
Do work for this issue in branch issue-#58.

* Save all images
* View the pages the images get rendered too and scale them down to the correct size

**Comment by s-rathyen** [comment]
![Uploading Screen Shot 2020-05-13 at 6.31.16 PM.png…]()

**Comment by s-rathyen** [comment]
<img width="1791" alt="Screen Shot 2020-05-13 at 6 31 16 PM" src="https://user-images.githubusercontent.com/38778256/81892944-0e667100-9548-11ea-8a72-a23c358bec02.png">
