### ISSUE TITLE
Change out Images with Images from Campus

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#59]
Do work for this issue in branch issue-#59.

Change the images site wide to be images from Campus.
* Include both grayscale and color photos in the repo.

**Comment by s-rathyen** [comment]
<img width="1791" alt="Screen Shot 2020-05-13 at 6 45 55 PM" src="https://user-images.githubusercontent.com/38778256/81894088-b2511c00-954a-11ea-8315-9c110eb7e7ed.png">
