### ISSUE TITLE
Restructure Landing Page

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#60]
Do work for this issue in branch issue-#60.

Change the user page to give the user more information on how to user the site and what they can do.

**Comment by s-rathyen** [comment]
![Uploading Screen Shot 2020-05-13 at 6.45.55 PM.png…]()

**Comment by s-rathyen** [comment]
<img width="1791" alt="Screen Shot 2020-05-13 at 6 45 55 PM" src="https://user-images.githubusercontent.com/38778256/81893806-17f0d880-954a-11ea-958f-849f1739f89e.png">
