### ISSUE TITLE
Restruture About Us Page

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#63]
Do work for this issue in branch issue-#63.

Change about us page to meet user feedback
* The icon spacing in the list

**Comment by s-rathyen** [comment]
<img width="1791" alt="Screen Shot 2020-05-13 at 6 50 10 PM" src="https://user-images.githubusercontent.com/38778256/81894047-9c435b80-954a-11ea-9eea-58eca947206d.png">
