### ISSUE TITLE
Have text wrap on the event cards

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#64]
Do work for this issue in branch issue-#64.

Currently the text does not wrap and displays across the window, have the text wrap and/or limit the characters displayed.

**Comment by s-rathyen** [comment]
<img width="1792" alt="Screen Shot 2020-05-10 at 5 21 24 PM" src="https://user-images.githubusercontent.com/38778256/81521404-da3e4680-92e2-11ea-8fb9-37bf53886400.png">
