### ISSUE TITLE
Edit EditProfile page to allow users to change their gender

### ISSUE THREAD

**Issue by pmccrind** [manoafitnessfinder/app#66]
Do work for this issue in branch issue-#66.

Allow the users to change their gender on the edit profile page.

**Comment by s-rathyen** [comment]
<img width="1792" alt="Screen Shot 2020-05-10 at 5 13 26 PM" src="https://user-images.githubusercontent.com/38778256/81520987-9ac32a80-92e1-11ea-9ac7-804572744b17.png">
