### ISSUE TITLE
Change out images with color images

### ISSUE THREAD

**Issue by cyuehara** [manoafitnessfinder/app#74]
Do work for this issue in branch issue-#74.
User feedback: Images on site felt dull 
* adding color images to the pages 
* resize images

**Comment by s-rathyen** [comment]
![Uploading Screen Shot 2020-05-13 at 6.45.55 PM.png…]()

**Comment by s-rathyen** [comment]
<img width="1791" alt="Screen Shot 2020-05-13 at 6 45 55 PM" src="https://user-images.githubusercontent.com/38778256/81893977-7ddd6000-954a-11ea-9af4-5bf36f2c32a2.png">
